### ISSUE TITLE
Add Japan support for Amazon Music

### ISSUE THREAD

**Issue by trustin** [tiliado/nuvola-app-amazon-cloud-player#46]
Thank you for a great project. It'd be awesome if Japan is added to the country variant list. :bow:

**Comment by a-m-s** [comment]
What's the URL for that, please?

**Comment by trustin** [comment]
It's https://music.amazon.co.jp

**Comment by a-m-s** [comment]
I've added an option to the preferences so you can set that as your "home" music site, but I can't check if the integration works because I don't speak Japanese and don't have an account at Amazon Japan.

This change will be included in the next Novula release (most likely). In the meantime, please use the "Load URL..." option from the Nuvola hamburger menu to navigate there yourself. It should already be accepted.

**Comment by a-m-s** [comment]
Please let me know if it works so I can close this issue.

**Comment by jiri-janousek** [comment]
I'm going to publish fresh packages tomorrow.

**Comment by jiri-janousek** [comment]
🍬 The feature was added to **Amazon Cloud Player script version 1.5.2** (2-g3a35663). It's already available in [📦 the Nuvola Player flatpak repository](https://nuvola.tiliado.eu/app/amazon_cloud_player/) (both stable and development branches). Thanks for reporting the issue :+1:
